@extends('layout')
@section('content')
<header><div><h1>Shield Wallet</h1><small>Signed in as {{ $user->name }}</small></div><form method="post" action="{{ route('logout') }}">@csrf<button class="secondary">Log out</button></form></header>
@if(session('success'))<div class="card success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="card error">{{ $errors->first() }}</div>@endif
<section class="card"><h2>Available balance</h2><div class="balance" id="balance" hidden>Rs. {{ number_format($wallet->balance_paisa / 100, 2) }}</div><button type="button" class="secondary" id="toggleBalance" onclick="const el=document.getElementById('balance'); el.hidden=!el.hidden; this.textContent=el.hidden?'Show balance':'Hide balance'">Show balance</button><p><small>Display hiding only; your authenticated account still has access to its balance.</small></p></section>
<div class="grid"><section class="card"><h2>Add beneficiary</h2><p>Look up a registered customer by email, then confirm.</p><form method="post" action="{{ route('beneficiaries.lookup') }}">@csrf<label>Email</label><input type="email" name="email" required><p><button class="secondary">Find customer</button></p></form>
@if(session('lookup'))<p>{{ session('lookup.name') }} ({{ session('lookup.email') }})</p><form method="post" action="{{ route('beneficiaries.store') }}">@csrf<input type="hidden" name="email" value="{{ session('lookup.email') }}"><button>Add beneficiary</button></form>@endif
<h3>My beneficiaries</h3>@forelse($recipients as $recipient)<p>{{ $recipient->name }} · {{ $recipient->email }} <form method="post" action="{{ route('beneficiaries.destroy', $recipient->id) }}">@csrf @method('DELETE')<button class="secondary">Remove</button></form></p>@empty<p>No beneficiaries yet.</p>@endforelse</section>
<section class="card"><h2>Send money</h2><form method="post" action="{{ route('transfer') }}">@csrf<input type="hidden" name="request_id" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><label>Beneficiary</label><select name="beneficiary_id" required><option value="">Select beneficiary</option>@foreach($recipients as $recipient)<option value="{{ $recipient->id }}">{{ $recipient->name }}</option>@endforeach</select><label>Amount (PKR)</label><input name="amount" inputmode="decimal" placeholder="2000.00" required><p><button>Confirm transfer</button></p></form><small>Transfers above Rs. 50,000, to a beneficiary under 24 hours old, or from an untrusted device are held pending FIDO2 and risk approval.</small></section></div>
<section class="card"><h2>Recent activity</h2><p><a href="{{ route('statement') }}">View full statement</a></p><table><thead><tr><th>Date</th><th>From</th><th>To</th><th>Amount</th><th>Receipt</th></tr></thead><tbody>@forelse($history as $t)<tr><td>{{ $t->created_at }}</td><td>{{ $t->sender_name }}</td><td>{{ $t->recipient_name }}</td><td>Rs. {{ number_format($t->amount_paisa / 100, 2) }}</td><td><a href="{{ route('receipt', $t->id) }}">View</a></td></tr>@empty<tr><td colspan="5">No transfers yet.</td></tr>@endforelse</tbody></table></section>
@endsection
